server:
  port: 8080

spring:
  application:
    name: customer-admin
  profiles:
    include: dev,qa,prod
    active: dev
  jackson:
    default-property-inclusion: non_empty
  webflux:
    base-path: /customer-admin

system:
  logging:
    file: /data/log/${spring.application.name}/${spring.application.name}.log
    format: "[%date{yyyy-MM-dd HH:mm:ss.SSS}{GMT+8}] [%-5level] [%X{trace_id}] [%class{0}:%method:%line] [%t] [-[%msg]-] %n"

logging:
  file:
    max-size: 500MB
    max-history: 7
    name: ${system.logging.file}
  pattern:
    file: ${system.logging.format}

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info" ]
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    info:
      enabled: true