server.port: 18088

#######################################
## 服务配置
#######################################
reactor.netty.ioSelectCount: 16
reactor.netty.ioWorkerCount: 128

common.cache.expireAfterWrite: 30
common.cache.expireAfterAccess: 30

logging.file.name: ${system.logging.file}
logging.pattern.console: "[%date{yyyy-MM-dd HH:mm:ss.SSS}{GMT+8}] [%-5level] [%X{trace_id}] [%class{0}:%method:%line] [%t] [%msg] %n"
logging.pattern.file: "[%date{yyyy-MM-dd HH:mm:ss.SSS}{GMT+8}] [%-5level] [%X{trace_id}] [%class{0}:%method:%line] [%t] [%msg] %n"

#########################
## 业务DB
#########################
spring.datasource.url: jdbc:mysql://10.101.110.111:13306/customer_admin?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.username: root
spring.datasource.password: 123456

spring.datasource.hikari.connection-timeout: 20000
spring.datasource.hikari.minimum-idle: 1
spring.datasource.hikari.maximum-pool-size: 4
spring.datasource.hikari.idle-timeout: 300000
spring.datasource.hikari.max-lifetime: 1200000
spring.datasource.hikari.auto-commit: true
spring.datasource.hikari.connection-test-query: "SELECT 1"
mybatis-plus.mapper-locations: classpath*:mapper/*.xml