server.port: 18091

#######################################
## 服务配置
#######################################
reactor.netty.ioSelectCount: 16
reactor.netty.ioWorkerCount: 128

common.cache.expireAfterWrite: 30
common.cache.expireAfterAccess: 30

logging.file.name: ${system.logging.file}
logging.pattern.file: "%date{ISO08601_OFFSET_DATE_TIME_HHCMM} %level [%thread] [%X{trace_id}] [%logger{10}#%method:%line] - %msg%n%throwable"
logging.pattern.console: "%date{ISO08601_OFFSET_DATE_TIME_HHCMM} %level [%thread] [%X{trace_id}] [%logger{10}#%method:%line] - %msg%n%throwable"

logging.level.org.springframework.security: DEBUG
############
## db
############
spring.datasource.url: jdbc:mysql://10.101.110.111:13306/mall_customer?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.username: root
spring.datasource.password: 123456

spring.datasource.hikari.connection-timeout: 20000
spring.datasource.hikari.minimum-idle: 1
spring.datasource.hikari.maximum-pool-size: 4
spring.datasource.hikari.idle-timeout: 300000
spring.datasource.hikari.max-lifetime: 1200000
spring.datasource.hikari.auto-commit: true
spring.datasource.hikari.connection-test-query: "SELECT 1"
mybatis-plus.mapper-locations: classpath*:mapper/*.xml
#*/
logging.level.com.winfred.mall.customer.mapper: debug

###################
## arthas
###################
spring.arthas.enabled: false
arthas.app-name: ${spring.application.name}
arthas.ip: 0.0.0.0
arthas.telnet-port: 3658
arthas.http-port: 18087
arthas.tunnel-server: ws://192.168.137.101:7777/ws
