server:
  port: 18080

spring:
  application:
    name: mall-customer
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_empty
  webflux:
    base-path: /mall-customer
  cloud:
    nacos:
      config:
        namespace: 2f68ef27-24f3-4331-96a0-a4a271b07b55
        server-addr: "nacos.server.local.xyz:8848"
        group: DEV_GROUP
        file-extension: yaml
      discovery:
        namespace: 2f68ef27-24f3-4331-96a0-a4a271b07b55
        server-addr: "nacos.server.local.xyz:8848"
        group: DEV_GROUP

system:
  logging:
    file: /data/log/${spring.application.name}/${spring.application.name}.log
    format: "%date{ISO08601_OFFSET_DATE_TIME_HHCMM} %level [%thread] [%X{trace_id}] [%logger{10}#%method:%line] - %msg%n%throwable"

logging:
  file:
    max-size: 500MB
    max-history: 7
    name: ${system.logging.file}
  pattern:
    file: ${system.logging.format}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health", "info" ]
      cros:
        allowed-methods: GET,POST
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    info:
      enabled: true
