server:
  port: 9000
  servlet:
    context-path: /mall-oauth2

spring:
  application:
    name: mall-oauth2
  cloud:
    nacos:
      config:
        namespace: 2f68ef27-24f3-4331-96a0-a4a271b07b55
        server-addr: "nacos.server.local.xyz:8848"
        group: DEV_GROUP
        file-extension: yaml
      discovery:
        namespace: 2f68ef27-24f3-4331-96a0-a4a271b07b55
        server-addr: "nacos.server.local.xyz:8848"
        group: DEV_GROUP

sys.service.log.dir: /data/logs/${spring.application.name}

logging:
  file:
    path: ${sys.service.log.dir}
    name: ${logging.file.path}/${spring.application.name}.log
    max-history: 7
    max-size: 521MB
  pattern:
    file: "%date{ISO08601_OFFSET_DATE_TIME_HHCMM} %level [%thread] [%X{trace_id}] [%logger{10}#%method:%line] - %msg%n%throwable"
    console: "%date{ISO08601_OFFSET_DATE_TIME_HHCMM} %level [%thread] [%X{trace_id}] [%logger{10}#%method:%line] - %msg%n%throwable"
  log4j2:
    config:
      override:

spring.datasource.url: jdbc:mysql://10.101.110.111:13306/oauth2_authorization_server?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.username: root
spring.datasource.password: 123456

spring.datasource.hikari.connection-timeout: 20000
spring.datasource.hikari.minimum-idle: 1
spring.datasource.hikari.maximum-pool-size: 4
spring.datasource.hikari.idle-timeout: 300000
spring.datasource.hikari.max-lifetime: 1200000
spring.datasource.hikari.auto-commit: true
spring.datasource.hikari.connection-test-query: "SELECT 1"

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info" ]
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    info:
      enabled: true
  arthas:
    enabled: false
