server:
  port: 8080
spring:
  application:
    name: gateway-shenyu
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: nacos.server.local.xyz:8848
        namespace: 5beca46a-fefe-4d03-9685-19f98ff2a121
      config:
        enabled: true
        server-addr: nacos.server.local.xyz:8848
        namespace: 5beca46a-fefe-4d03-9685-19f98ff2a121

shenyu:
  sync:
    websocket:
      urls: ws://shenyua-dmin.server.local.xyz:9095/websocket  # shenyu-admin 地址